### PR TITLE
Use Adopt OpenJDK (and env matrix)

### PR DESCRIPTION
**Pull request by ennru**
As matrix and stages don't like each other.

### CODE REVIEW

**Comment by mkurz** [comment]
@ennru Are you aware that you just published `v0.5.1` already, which was just available via
https://github.com/sbt/sbt-java-formatter/releases/tag/v0.5.1 and also you pushed that tag/commit to the public git repo? Not sure if it is a good idea to force remove that tag and commits, since it's public...

**Comment by ennru** [comment]
Yes, I'm aware. The auto release broke with the introduction of the build matrix. I'm trying to fix that so that we actually publish a release...

**Comment by mkurz** [comment]
BTW: This is how Play solves this:
https://github.com/playframework/playframework/blob/0021598ae46bc94adba2ae1fc3b1663e3fdf4354/.travis.yml#L21-L25
and the matrix:
https://github.com/playframework/playframework/blob/0021598ae46bc94adba2ae1fc3b1663e3fdf4354/.travis.yml#L18-L19

**Comment by mkurz** [comment]
And it caches:
https://github.com/playframework/playframework/blob/0021598ae46bc94adba2ae1fc3b1663e3fdf4354/.travis.yml#L124

**Comment by mkurz** [comment]
Also just thre days there was this fix: https://github.com/playframework/playframework/pull/10101

**Comment by ennru** [comment]
The stages are off. I don't have more time to put into this, I'm afraid.

**Comment by mkurz** [comment]
Build is green, ready for release :wink:

**Comment by ennru** [comment]
No, I didn't expect three steps in the build...

**Comment by ennru** [comment]
I think we do not necessarily need to verify this tiny plugin on JDK 11.

**Pull request closed without merging**
